### ISSUE TITLE
1.20  --4g-alloc-size 4080 not working

### ISSUE THREAD

**Issue by icelove88** [Lolliedieb/lolMiner-releases#176]
in 1.19 -4g-alloc-size 4080 is OK.

**Comment by jgonzis** [comment]
are you trying to run it with also dualmining?... if you can give more extra information which OS...? which error gives in 1.20... That could help to know what's happening...

**Comment by icelove88** [comment]
miner os 
2021-01-25 19:25:24,633 [INFO] start miner app...
Traceback (most recent call last):
  File "/opt/minerapp/usr/bin/lolminer.py", line 142, in <module>
    main()
  File "/opt/minerapp/usr/bin/lolminer.py", line 138, in main
    app.run()
  File "/opt/minerapp/usr/bin/mos/miner.py", line 219, in run
    miner = Miner(self)
  File "/opt/minerapp/usr/bin/mos/miner.py", line 129, in __init__
    self.cmdline = self.app.get_cmd_line()
  File "/opt/minerapp/usr/bin/lolminer.py", line 111, in get_cmd_line
    algo = search_algo.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by icelove88** [comment]
Btw, when try to remove the  whole "-4g-alloc-size 4080" . 1.20.1 can working but the speed is lower than 1.19.

**Comment by jgonzis** [comment]
that seems to be a problem of MinerOS... these line are Python scripts of Miner OS I suppose they don't update correctly the parameters...  for you information you put it seem you didn't put the 2 -- only 1... that could be also the problem
